# Generated by Django 4.2 on 2023-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('secondtitle', models.CharField(max_length=255)),
                ('firstDisc', models.CharField(max_length=255)),
                ('secondDisc', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('mainDisc', models.CharField(max_length=255)),
                ('firstImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('secondImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thirdImage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ['-createdAT'],
            },
        ),
    ]
