# Generated by Django 4.2 on 2023-04-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_firstdisc_alter_product_maindisc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['createdAT'], 'verbose_name_plural': 'Product'},
        ),
        migrations.AddField(
            model_name='product',
            name='divsId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hrefId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
