# Generated by Django 4.2 on 2023-04-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='divsId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hrefId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
