# Generated by Django 4.2 on 2023-04-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_divsid_alter_product_hrefid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='divsId',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hrefId',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
