# Generated by Django 4.2.1 on 2023-06-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Order'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip',
        ),
    ]
