# Generated by Django 4.2.1 on 2023-06-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zip',
        ),
    ]
