# Generated by Django 4.2.1 on 2023-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_order_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
